"""Run the Cycle 9 MusicXML and player-packet integrity demo."""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from io import BytesIO
from pathlib import Path
from zipfile import ZipFile

from bandforge_domain.arrangements import build_arrangement_seed
from bandforge_domain.chart import StructuredChartInput, normalize_chart
from bandforge_domain.generator import ArrangementControls, generate_candidate
from bandforge_domain.notation import export_candidate_musicxml, validate_musicxml
from bandforge_domain.packets import build_player_packet, validate_player_packet

ROOT = Path(__file__).parents[1]


def main() -> int:
    chart = normalize_chart(
        StructuredChartInput(
            title="Cycle 9 Authored Fixture",
            key="A_MINOR",
            bars=["Am", "F", "C", "G"],
        )
    )
    source = build_arrangement_seed(
        chart,
        "src_rev_cycle9_demo",
        "sha256:" + "2" * 64,
        datetime(2026, 7, 19, tzinfo=UTC),
        arrangement_id="arrangement_cycle9_demo",
        version_id="version_cycle9_demo",
    )
    generated = generate_candidate(source, ArrangementControls(seed=29, tempo_bpm=108))
    if not generated.accepted:
        raise RuntimeError(f"demo candidate was rejected: {generated.findings}")

    notation = export_candidate_musicxml(generated.document)
    notation_validation = validate_musicxml(notation.data, generated.document)
    packet = build_player_packet(generated.document)
    packet_validation = validate_player_packet(packet.data, generated.document)
    replay = export_candidate_musicxml(generated.document)
    replay_packet = build_player_packet(generated.document)
    reports_dir = ROOT / "reports"
    musicxml_path = reports_dir / "cycle-9-score.musicxml"
    packet_path = reports_dir / "cycle-9-player-packet.zip"
    manifest_path = reports_dir / "cycle-9-player-packet-manifest.json"
    musicxml_path.write_bytes(notation.data)
    packet_path.write_bytes(packet.data)
    manifest_path.write_bytes(
        (json.dumps(packet.manifest, sort_keys=True, separators=(",", ":")) + "\n").encode(
            "utf-8"
        )
    )
    saved_musicxml = musicxml_path.read_bytes()
    saved_packet = packet_path.read_bytes()
    saved_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    with ZipFile(BytesIO(saved_packet), "r") as saved_archive:
        embedded_manifest = json.loads(saved_archive.read("manifest.json"))
    saved_notation_validation = validate_musicxml(saved_musicxml, generated.document)
    saved_packet_validation = validate_player_packet(saved_packet, generated.document)
    if saved_manifest != packet.manifest or saved_manifest != embedded_manifest:
        raise RuntimeError("saved packet manifest does not match generated packet data")
    if saved_musicxml != notation.data or saved_packet != packet.data:
        raise RuntimeError("saved artifact bytes do not match generated bytes")
    evidence = {
        "sourceRevisionId": source["sourceRefs"][0]["sourceRevisionId"],
        "candidateAccepted": generated.accepted,
        "acceptedVersionId": generated.document["versionId"],
        "musicxml": {
            "format": notation.manifest["format"],
            "bytes": len(notation.data),
            "sha256": "sha256:" + hashlib.sha256(notation.data).hexdigest(),
            "validation": notation_validation,
            "savedPath": str(musicxml_path.relative_to(ROOT)),
            "savedBytes": len(saved_musicxml),
            "savedSha256": "sha256:" + hashlib.sha256(saved_musicxml).hexdigest(),
            "savedValidation": saved_notation_validation,
            "manifest": notation.manifest,
            "deterministicReplay": notation.data == replay.data,
        },
        "playerPacket": {
            "bytes": len(packet.data),
            "sha256": "sha256:" + hashlib.sha256(packet.data).hexdigest(),
            "validation": packet_validation,
            "savedPath": str(packet_path.relative_to(ROOT)),
            "savedBytes": len(saved_packet),
            "savedSha256": "sha256:" + hashlib.sha256(saved_packet).hexdigest(),
            "savedValidation": saved_packet_validation,
            "manifestPath": str(manifest_path.relative_to(ROOT)),
            "manifest": packet.manifest,
            "deterministicReplay": packet.data == replay_packet.data,
        },
        "rightsAttested": notation.manifest["rightsAttested"],
        "sourceHarmonyPreserved": generated.document["harmony"] == source["harmony"],
    }
    report = ROOT / "reports" / "cycle-9-notation-packet-demo.md"
    report.write_text(
        "# Cycle 9 MusicXML and Player-Packet Integrity Demo\n\n"
        "Authored source fixture: `Am | F | C | G`; no title lookup, streaming metadata, "
        "or model call supplied musical content.\n\n"
        f"```json\n{json.dumps(evidence, indent=2)}\n```\n\n"
        "This demonstrates deterministic MusicXML 4.0 score-partwise bytes, 960-tick "
        "structural smoke validation, and a deterministic ZIP packet with manifest hashes, "
        "source revision IDs, accepted version, rights attestation, and generation lineage. "
        "It does not claim browser rendering, readable engraving, playability, PDF, signed "
        "downloads, transposition, or audio playback.\n",
        encoding="utf-8",
    )
    print(json.dumps(evidence, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
